### ISSUE TITLE
Request for songs data till 2019

### ISSUE THREAD

**Issue by KushRJ** [jsubroto/billboard-hot-100-web-scraper#1]
Could you provide the data till 2019? It would be really helpful.
Furthermore, could you tell me how do I convert the .json files to a format which can be used by a deep learning model?

Thank You

**Comment by jsubroto** [comment]
Hi @KushRJ,

You can add the date you want to the URL to get the list for specific dates.
I'm not sure about your question on the .json file since my app scrapes the list into a CSV file.
